UPDATE symbols
SET is_active = CASE asset_code
    WHEN 'HYPE' THEN FALSE
    WHEN 'LEO' THEN FALSE
    WHEN 'XMR' THEN FALSE
    WHEN 'CC' THEN FALSE
    WHEN 'CRO' THEN FALSE
    WHEN 'OKB' THEN FALSE
    WHEN 'M' THEN FALSE
    WHEN 'MNT' THEN FALSE
    WHEN 'PI' THEN FALSE
    WHEN 'BGB' THEN FALSE
    WHEN 'KCS' THEN FALSE
    WHEN 'KAS' THEN FALSE
    ELSE TRUE
END,
updated_at = NOW();
