INSERT INTO timeframes (code, duration_sec, is_active)
VALUES
    ('15m', 900, TRUE),
    ('1h', 3600, TRUE),
    ('4h', 14400, TRUE)
ON CONFLICT (code) DO UPDATE
SET duration_sec = EXCLUDED.duration_sec,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

INSERT INTO symbols (asset_code, name, market_cap_rank, quote_asset, binance_symbol, is_active)
VALUES
    ('BTC', 'BTC', 1, 'USDT', 'BTCUSDT', TRUE),
    ('ETH', 'ETH', 2, 'USDT', 'ETHUSDT', TRUE),
    ('BNB', 'BNB', 3, 'USDT', 'BNBUSDT', TRUE),
    ('XRP', 'XRP', 4, 'USDT', 'XRPUSDT', TRUE),
    ('SOL', 'SOL', 5, 'USDT', 'SOLUSDT', TRUE),
    ('TRX', 'TRX', 6, 'USDT', 'TRXUSDT', TRUE),
    ('HYPE', 'HYPE', 7, 'USDT', 'HYPEUSDT', FALSE),
    ('DOGE', 'DOGE', 8, 'USDT', 'DOGEUSDT', TRUE),
    ('LEO', 'LEO', 9, 'USDT', 'LEOUSDT', FALSE),
    ('ZEC', 'ZEC', 10, 'USDT', 'ZECUSDT', TRUE),
    ('XLM', 'XLM', 11, 'USDT', 'XLMUSDT', TRUE),
    ('ADA', 'ADA', 12, 'USDT', 'ADAUSDT', TRUE),
    ('XMR', 'XMR', 13, 'USDT', 'XMRUSDT', FALSE),
    ('LINK', 'LINK', 14, 'USDT', 'LINKUSDT', TRUE),
    ('CC', 'CC', 15, 'USDT', 'CCUSDT', FALSE),
    ('GRAM', 'GRAM', 16, 'USDT', 'GRAMUSDT', TRUE),
    ('BCH', 'BCH', 17, 'USDT', 'BCHUSDT', TRUE),
    ('LTC', 'LTC', 18, 'USDT', 'LTCUSDT', TRUE),
    ('HBAR', 'HBAR', 19, 'USDT', 'HBARUSDT', TRUE),
    ('SUI', 'SUI', 20, 'USDT', 'SUIUSDT', TRUE),
    ('AVAX', 'AVAX', 21, 'USDT', 'AVAXUSDT', TRUE),
    ('CRO', 'CRO', 22, 'USDT', 'CROUSDT', FALSE),
    ('NEAR', 'NEAR', 23, 'USDT', 'NEARUSDT', TRUE),
    ('SHIB', 'SHIB', 24, 'USDT', 'SHIBUSDT', TRUE),
    ('XAUT', 'XAUt', 25, 'USDT', 'XAUTUSDT', TRUE),
    ('DEXE', 'DEXE', 26, 'USDT', 'DEXEUSDT', TRUE),
    ('TAO', 'TAO', 27, 'USDT', 'TAOUSDT', TRUE),
    ('UNI', 'UNI', 28, 'USDT', 'UNIUSDT', TRUE),
    ('PAXG', 'PAXG', 29, 'USDT', 'PAXGUSDT', TRUE),
    ('WLFI', 'WLFI', 30, 'USDT', 'WLFIUSDT', TRUE),
    ('ASTER', 'ASTER', 31, 'USDT', 'ASTERUSDT', TRUE),
    ('OKB', 'OKB', 32, 'USDT', 'OKBUSDT', FALSE),
    ('ONDO', 'ONDO', 33, 'USDT', 'ONDOUSDT', TRUE),
    ('M', 'M', 34, 'USDT', 'MUSDT', FALSE),
    ('DOT', 'DOT', 35, 'USDT', 'DOTUSDT', TRUE),
    ('WLD', 'WLD', 36, 'USDT', 'WLDUSDT', TRUE),
    ('AAVE', 'AAVE', 37, 'USDT', 'AAVEUSDT', TRUE),
    ('MNT', 'MNT', 38, 'USDT', 'MNTUSDT', FALSE),
    ('SKY', 'SKY', 39, 'USDT', 'SKYUSDT', TRUE),
    ('PI', 'PI', 40, 'USDT', 'PIUSDT', FALSE),
    ('ICP', 'ICP', 41, 'USDT', 'ICPUSDT', TRUE),
    ('BGB', 'BGB', 42, 'USDT', 'BGBUSDT', FALSE),
    ('ETC', 'ETC', 43, 'USDT', 'ETCUSDT', TRUE),
    ('PEPE', 'PEPE', 44, 'USDT', 'PEPEUSDT', TRUE),
    ('MORPHO', 'MORPHO', 45, 'USDT', 'MORPHOUSDT', TRUE),
    ('KCS', 'KCS', 46, 'USDT', 'KCSUSDT', FALSE),
    ('KAS', 'KAS', 47, 'USDT', 'KASUSDT', FALSE),
    ('RENDER', 'RENDER', 48, 'USDT', 'RENDERUSDT', TRUE),
    ('ATOM', 'ATOM', 49, 'USDT', 'ATOMUSDT', TRUE),
    ('QNT', 'QNT', 50, 'USDT', 'QNTUSDT', TRUE)
ON CONFLICT (asset_code) DO UPDATE
SET name = EXCLUDED.name,
    market_cap_rank = EXCLUDED.market_cap_rank,
    quote_asset = EXCLUDED.quote_asset,
    binance_symbol = EXCLUDED.binance_symbol,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
